[package]
name = "ndk-examples"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
publish = false

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { path = "../ndk-glue" }
ndk = { path = "../ndk", features = ["trace"] }

[[example]]
name = "hello_world"
crate-type = ["cdylib"]
